name: Schedule Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  job1:
    name: first Job
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "Hello"

      - name: Print Goodbye
        run: echo "Goodbye"

